name: Análisis y pruebas de código en Python

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Verificar formato con Black
        run: |
          source venv/bin/activate
          black --check src tests

      - name: Verificar importaciones con isort
        run: |
          source venv/bin/activate
          isort . --check-only

      - name: Verificar errores de estilo con Flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Ejecutar pruebas
        run: |
          source venv/bin/activate
          pytest tests/
